name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.15.5

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: node app.js

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.15.5

      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Create Deployment Artifact
        run: zip -r deployment.zip .
